### ISSUE TITLE
Assignment 3 - completed parts a and b - have done commit but cannot push = Error 403

### ISSUE THREAD

**Issue by andypeal** [ds4owd-001/md-03-assignments-andypeal#1]
@larnsce @mianzg @sskorik01 
Hi 
on Assignment 3 - I have completed parts a and b 
I have done commit but cannot push
I get an Error 403 as per the attached message 

![Git push error code 403](https://github.com/ds4owd-001/md-03-assignments-andypeal/assets/149708012/9ec05e84-32c6-420e-b90a-ee2150bbdeb9)

I have used my PAT password (and worked before) - any suggestions?
Andy

**Comment by larnsce** [comment]
Thank you, @andypeal. You only have "read" access to this repo and not "write". I don't know why, because you also accepted the invitation to the GitHub Orgnaisation.

I have now reset your access to this repository and invited you again as a collaborator with "write" access, which should allow you to push after you accepted that invitation.

Can you check your email if something from GitHub has come in?

**Comment by andypeal** [comment]
@larnsce - great thanks - that solved it :-)

**Comment by larnsce** [comment]
Happy to know that. I will close the issue now.
